<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Students Cleared - {{ $academicYear->academic_year }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        .header h2 {
            margin: 5px 0;
            font-size: 16px;
            color: #666;
        }
        .info {
            margin-bottom: 20px;
        }
        .info p {
            margin: 5px 0;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
            font-size: 11px;
        }
        td {
            font-size: 10px;
        }
        .text-center {
            text-align: center;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        @media print {
            body {
                margin: 0;
            }
            .no-print {
                display: none;
            }
        }
        .osa-notice {
            background-color: #e8f5e8;
            border: 1px solid #28a745;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 4px;
        }
        .osa-notice strong {
            color: #28a745;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>ST. PAUL UNIVERSITY PHILIPPINES</h1>
        <h2>Students Cleared Report</h2>
        <p>Academic Year: {{ $academicYear->academic_year }}</p>
        @if($department)
            <p>Department: {{ $department->department_name }}</p>
        @else
            <p>Department: All Departments</p>
        @endif
    </div>

    <div class="osa-notice">
        <strong>OSA Employee Report:</strong> This report was generated by an Office of Student Affairs (OSA) employee.
    </div>

    <div class="info">
        <p>Report Generated: {{ now()->format('F d, Y - h:i A') }}</p>
        <p>Total Students Cleared: {{ count($clearedStudents) }}</p>
        <p>Generated by: {{ auth()->user()->firstname }} {{ auth()->user()->lastname }} (OSA)</p>
    </div>

    @if(count($clearedStudents) > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 15%;">Student Number</th>
                    <th style="width: 30%;">Name</th>
                    <th style="width: 25%;">Department</th>
                    <th style="width: 20%;">Program</th>
                    <th style="width: 10%;">Year</th>
                </tr>
            </thead>
            <tbody>
                @foreach($clearedStudents as $student)
                    <tr>
                        <td>{{ $student->student_number }}</td>
                        <td>{{ $student->user ? $student->user->lastname . ', ' . $student->user->firstname . ' ' . $student->user->middlename : 'N/A' }}</td>
                        <td>{{ $student->department ? $student->department->department_name : 'N/A' }}</td>
                        <td>{{ $student->courses ? $student->courses->course_name : 'N/A' }}</td>
                        <td class="text-center">{{ $student->year ?? 'N/A' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="text-center" style="margin: 50px 0; color: #666;">
            <p>No students found who have cleared for the selected criteria.</p>
        </div>
    @endif

    <div class="footer">
        <p>This report is generated from the SPUP Clearance Management System</p>
        <p>Office of Student Affairs (OSA) - Authorized Personnel Only</p>
        <p>{{ now()->format('F d, Y - h:i A') }}</p>
    </div>

    <script>
        // Auto-print when page loads
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>
