<!DOCTYPE html>
<html>
<head>
    <title>Students Cleared - Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .info { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; }
        @media print {
            .no-print { display: none; }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Students Who Have Cleared</h1>
        <h3>{{ $academicYear->academic_year }} - {{ $academicYear->semester }}</h3>
        @if($department)
            <h4>Department: {{ $department->name }}</h4>
        @endif
    </div>

    <div class="info">
        <p><strong>Generated on:</strong> {{ now()->format('F d, Y h:i A') }}</p>
        <p><strong>Total Students:</strong> {{ $clearedStudents->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Student Number</th>
                <th>Name</th>
                <th>Department</th>
                <th>Program</th>
                <th>Year</th>
                <th>Cleared Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($clearedStudents as $index => $student)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $student->student_number }}</td>
                <td>{{ $student->user->firstname }} {{ $student->user->lastname }}</td>
                <td>{{ $student->department->name }}</td>
                <td>{{ $student->courses->course_name ?? 'N/A' }}</td>
                <td>{{ $student->year }}</td>
                <td>
                    @php
                        $clearance = $student->clearances()->latest()->first();
                    @endphp
                    {{ $clearance ? $clearance->updated_at->format('M d, Y') : 'N/A' }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated by the Clearance Management System</p>
    </div>

    <div class="no-print" style="margin-top: 20px; text-align: center;">
        <button onclick="window.print()" class="btn btn-primary">Print Report</button>
        <button onclick="window.close()" class="btn btn-secondary">Close</button>
    </div>

    <script>
        // Auto print when page loads
        window.onload = function() {
            window.print();
        }
    </script>
</body>
</html>
